### ISSUE TITLE
文件上传报错

### ISSUE THREAD

**Issue by llocry** [webman-tech/laravel-filesystem#1]
根据教程调用报错LaravelUploadedFile::wrapper($request->file('avatar'))->store('avatars')
报错信息：
Webman\Exception\NotFoundException: Class 'Illuminate\Contracts\Filesystem\Factory' not found in /chancemall/webman/vendor/workerman/webman-framework/src/Container.php:36

报错详细信息：
https://www.workerman.net/q/9506

**Comment by krissss** [comment]
配置一下 `config/plugin/webman-tech/polyfill/app.php` 下的 `laravel > filesystem` 返回

```php
'laravel' => [
        /**
         * 如果用到 Laravel UploadedFile 中的 store 或 storeAs 相关方法，需要提供 filesystemFactory 实现
         */
        'filesystem' => function (): FilesystemFactory {
            return \WebmanTech\LaravelFilesystem\Facades\Storage::instance(); // 该实现
        },
]
```

**Comment by llocry** [comment]
感谢答疑，已经解决了

**Comment by llocry** [comment]
感谢🙏
