### ISSUE TITLE
对象存储的文件如何下载?

### ISSUE THREAD

**Issue by iYting** [webman-tech/laravel-filesystem#2]
我在filesystems.php中把七牛云设置default  
文件上传时可以正常上传, 
但是使用download和url方法却提示
 **Call to undefined method League\\Flysystem\\Filesystem::download**
`Storage::url($file)`
`Storage::download($file)`

请问是不支持对象存储文件的下载和url获取吗?

**Comment by krissss** [comment]
laravel 9 以下还是以上版本的？

**Comment by krissss** [comment]
提供一下完整的 composer.json 相关的几个包信息

**Comment by iYting** [comment]
![image](https://user-images.githubusercontent.com/17744874/197151502-38b73690-4a3d-437c-a2d4-5bd0b7be2bb6.png)
![image](https://user-images.githubusercontent.com/17744874/197151682-c55673c1-7665-4089-9956-e9594573fa1d.png)

**Comment by krissss** [comment]
更新到 2.1.4 试一下

**Comment by iYting** [comment]
完美解决了
